name: Image build Callback Action
description: 'Image build Callback Action'

inputs:
  slsa-workflow-inputs:
    description: 'All the inputs formatted as a map'
    type: string
    required: true

  slsa-layout-file:
    description: 'Location to store the layout content'
    type: string
    required: true

  slsa-workflow-secret1: {}
  slsa-workflow-secret2: {}
  slsa-workflow-secret3: {}
  slsa-workflow-secret4: {}
  slsa-workflow-secret5: {}
  slsa-workflow-secret6: {}
  slsa-workflow-secret7: {}
  slsa-workflow-secret8: {}
  slsa-workflow-secret9: {}
  slsa-workflow-secret10: {}
  slsa-workflow-secret11: {}
  slsa-workflow-secret12: {}
  slsa-workflow-secret13: {}
  slsa-workflow-secret14: {}
  slsa-workflow-secret15: {}

outputs:
  image:
    description: The path to the built image.
    value: ${{ steps.build.outputs.image }}

runs:
  using: composite
  steps:

    - name: Run main Action
      uses: Laerson/hpe-secure-pipeline-demo/.github/actions/build-image@main
      id: build
      with:
        image:  ${{ fromJson(inputs.slsa-workflow-inputs).image }}
        working-directory:  ${{ fromJson(inputs.slsa-workflow-inputs).working-directory }}

    - name: Generate layout file
      id: generate-layout
      env:
        SLSA_OUTPUTS_ARTIFACTS_FILE: ${{ inputs.slsa-layout-file }}
        ARTIFACT: ${{ fromJson(inputs.slsa-workflow-inputs).image }}
      shell: bash
      run: |
        ./../__TOOL_ACTION_DIR__/generate-layout.sh        
    