name: Vulnerability Scan With Syft

inputs:
  slsa-workflow-inputs:
    description: 'All the inputs formatted as a map'
    type: string
    required: true

  slsa-layout-file:
    description: 'Location to store the layout content'
    type: string
    required: true

  slsa-workflow-secret1: {}
  slsa-workflow-secret2: {}
  slsa-workflow-secret3: {}
  slsa-workflow-secret4: {}
  slsa-workflow-secret5: {}
  slsa-workflow-secret6: {}
  slsa-workflow-secret7: {}
  slsa-workflow-secret8: {}
  slsa-workflow-secret9: {}
  slsa-workflow-secret10: {}
  slsa-workflow-secret11: {}
  slsa-workflow-secret12: {}
  slsa-workflow-secret13: {}
  slsa-workflow-secret14: {}
  slsa-workflow-secret15: {}

outputs:
  results:
    description: The path to the vulnerability scan results.
    value: ${{ steps.build.outputs.results }}

runs:
  using: composite
  steps:

    - name: Run main Action
      uses: Laerson/hpe-secure-pipeline-demo/.github/actions/vuln-scan@main
      id: build
      with:
        sbom:  ${{ fromJson(inputs.slsa-workflow-inputs).sbom }}
        severity-cutoff:  ${{ fromJson(inputs.slsa-workflow-inputs).severity-cutoff }}
        results:  ${{ fromJson(inputs.slsa-workflow-inputs).results }}

    - name: Generate layout file
      id: generate-layout
      env:
        SLSA_OUTPUTS_ARTIFACTS_FILE: ${{ inputs.slsa-layout-file }}
        ARTIFACT: ${{ fromJson(inputs.slsa-workflow-inputs).results }}
      shell: bash
      run: |
        ./../__TOOL_ACTION_DIR__/generate-layout.sh

    # We need a unique artifact name per workflow run, to avoid name collisions
    # when sharing artifacts, e.g. when multiple workflows run concurrently.
    - name: Create random value
      id: rng
      # WARNING: This is not cryptographically secure and will show in logs!
      uses: slsa-framework/slsa-github-generator/actions/delegator/random@v1.9.0

    # Create the folder to share.
    # The folder is local, so need its name needs not be randomized.
    - name: Create folder to share
      shell: bash
      env:
        ARTIFACT: "${{ fromJson(inputs.slsa-workflow-inputs).results }}"
      run: |
        set -euo pipefail

        mkdir artifacts
        mv "${ARTIFACT}" artifacts/

    # Share the artifacts folder, with a unique randomized name.
    - name: Share artifacts
      id: upload
      uses: slsa-framework/slsa-github-generator/actions/delegator/secure-upload-folder@v1.9.0
      with:
        name: "${{ steps.rng.outputs.random }}-artifacts"
        path: artifacts      
    