name: Sast Callback Action
description: 'SAST Callback Action'

inputs:
  slsa-workflow-inputs:
    description: 'All the inputs formatted as a map'
    type: string
    required: true

  slsa-layout-file:
    description: 'Location to store the layout content'
    type: string
    required: true

  slsa-workflow-secret1: {}
  slsa-workflow-secret2: {}
  slsa-workflow-secret3: {}
  slsa-workflow-secret4: {}
  slsa-workflow-secret5: {}
  slsa-workflow-secret6: {}
  slsa-workflow-secret7: {}
  slsa-workflow-secret8: {}
  slsa-workflow-secret9: {}
  slsa-workflow-secret10: {}
  slsa-workflow-secret11: {}
  slsa-workflow-secret12: {}
  slsa-workflow-secret13: {}
  slsa-workflow-secret14: {}
  slsa-workflow-secret15: {}

outputs:
  sast-results:
    description: The path to the sast results.
    value: ${{ steps.output_results.outputs.sast-results }}

runs:
  using: composite
  steps:

    - name: Run main Action
      uses: Laerson/hpe-secure-pipeline-demo/.github/actions/sast@main
      id: build
      with:
        rules:  ${{ fromJson(inputs.slsa-workflow-inputs).rules }}
        suppression-rules:  ${{ fromJson(inputs.slsa-workflow-inputs).suppression-rules }}
        results:  ${{ fromJson(inputs.slsa-workflow-inputs).results }}

    - name: Generate layout file
      id: generate-layout
      env:
        SLSA_OUTPUTS_ARTIFACTS_FILE: ${{ inputs.slsa-layout-file }}
        ARTIFACT: ${{ fromJson(inputs.slsa-workflow-inputs).results }}
      shell: bash
      run: ./../__TOOL_ACTION_DIR__/generate-layout.sh  
        
    